Delivered-To: mikeb01@gmail.com
Received: by 10.90.31.5 with SMTP id e5cs146651age; Fri, 2 Feb 2007
	16:31:42 -0800 (PST)
Received: by 10.49.57.12 with SMTP id j12mr2038278nfk.1170462702093; Fri,
	02 Feb 2007 16:31:42 -0800 (PST)
Return-Path: <acoliver@buni.org>
Received: from mx2.turbodns.co.uk (mx2.turbodns.co.uk [81.21.76.59]) by
	mx.google.com with SMTP id g1si17153395nfe.2007.02.02.16.31.41; Fri, 02 Feb
	2007 16:31:42 -0800 (PST)
Received-SPF: neutral (google.com: 81.21.76.59 is neither permitted nor
	denied by best guess record for domain of acoliver@buni.org)
Received: (qmail 29865 invoked by uid 68); 3 Feb 2007 00:31:41 -0000
Delivered-To: middlesoft-mike@middlesoft.co.uk
Received: (qmail 29862 invoked by uid 1024); 3 Feb 2007 00:31:41 -0000
Received: from acoliver@buni.org by server26.donhost.co.uk by uid 1002 with
	qmail-scanner-1.22  ( Clear:RC:0(70.85.159.210):.  Processed in 0.586036
	secs); 03 Feb 2007 00:31:41 -0000
Received: from unknown (HELO ?216.21.229.197?) (70.85.159.210) by
	192.168.147.20 with SMTP; 3 Feb 2007 00:31:40 -0000
Return-Path: <acoliver@buni.org>
Received: from [192.168.3.2] (cpe-071-077-006-045.nc.res.rr.com 71.77.6.45)
	by Received: from [192.168.3.2] (cpe-071-077-006-045.nc.res.rr.com
	71.77.6.45) by mail.buni.org/Meldware Mail 1.0M7-pre (70.85.159.212) with
	SMTP id 1170462855309958.854948755212; Fri, 2 Feb 2007 18:34:15 -0600 (CST)
Message-ID: <45C3D812.80605@buni.org>
Date: Fri, 02 Feb 2007 19:32:18 -0500
From: "Andrew C. Oliver" <acoliver@buni.org>
User-Agent: Thunderbird 1.5.0.9 (X11/20070103)
MIME-Version: 1.0
To: Michael Barker <mike@middlesoft.co.uk>
Subject: [Fwd: [internetworkers] February TriLUG meeting: Greg
	Dekoenigsberg on	One]
Content-Type: multipart/mixed; boundary="------------010508010705020604050502"
X-Evolution-Source: pop://mikeb01@pop.gmail.com/

This is a multi-part message in MIME format.
--------------010508010705020604050502
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 8bit

this mail came out blank in imap..

--------------010508010705020604050502
Content-Type: message/rfc822; name*0="[internetworkers] February TriLUG meeting: Greg Dekoenigsberg on"; name*1="	One"
Content-Transfer-Encoding: 7bit
Content-Disposition: inline; filename*0="[internetworkers] February TriLUG meeting: Greg Dekoenigsber"; filename*1="g on	One"

Received: from malecky (unknown [152.46.7.119])	by metalab.unc.edu
	(Postfix) with ESMTP id B33314899A;	Fri,  2 Feb 2007 18:25:09 -0500 (EST)
Received: from ug-out-1314.google.com (ug-out-1314.google.com
	[66.249.92.174])	by Received: from ug-out-1314.google.com
	(ug-out-1314.google.com [66.249.92.174])	by lists.ibiblio.org (Postfix)
	with ESMTP id B4ABF4C00F	for <internetworkers@lists.ibiblio.org>;	Fri, 2
	Feb 2007 18:25:05 -0500 (EST)
Received: by ug-out-1314.google.com with SMTP id 34so931141ugf	for
	<internetworkers@lists.ibiblio.org>;	Fri, 02 Feb 2007 15:25:05 -0800 (PST)
Received: by 10.82.175.2 with SMTP id x2mr1450209bue.1170458704081;	Fri, 02
	Feb 2007 15:25:04 -0800 (PST)
Received: by 10.82.127.12 with HTTP; Fri, 2 Feb 2007 15:25:04 -0800 (PST)
Received: from metalab.unc.edu (mail.metalab.unc.edu 152.46.7.112) by
	mail.buni.org/Meldware Received: from metalab.unc.edu (mail.metalab.unc.edu
	152.46.7.112) by mail.buni.org/Meldware Mail 1.0M7-pre (70.85.159.212) with
	SMTP id 1170462071762123.93846549734212; Fri, 2 Feb 2007 18:21:11 -0600
	(CST)
X-Original-To: internetworkers@lists.ibiblio.org
Delivered-To: internetworkers@lists.ibiblio.org
Message-ID: <39e2ba090702021524l78930754r11242a1b1197c95c@mail.gmail.com>
Date: Fri, 2 Feb 2007 18:25:04 -0500
From: "=?UTF-8?Q?Crist=C3=B3bal_Palmer?=" <cristobalpalmer@gmail.com>
To: "Triangle Linux Users Group discussion list" <trilug@trilug.org>,	trilug-announce@trilug.org,	"Internetworkers: http://www.ibiblio.org/internetworkers/" <internetworkers@lists.ibiblio.org>,	tribug-members@tribug.org
MIME-Version: 1.0
Content-Type: multipart/mixed;	boundary="----=_Part_29756_30378337.1170458704014"
Subject: [internetworkers] February TriLUG meeting: Greg Dekoenigsberg
	on	One Laptop Per Child
X-BeenThere: internetworkers@lists.ibiblio.org
X-Mailman-Version: 2.1.9
Precedence: list
Reply-To: "Internetworkers: http://www.ibiblio.org/internetworkers/" <internetworkers@lists.ibiblio.org>
List-Id: "Internetworkers:
	http://www.ibiblio.org/internetworkers/"	<internetworkers.lists.ibiblio.org>
List-Unsubscribe:
	<http://lists.ibiblio.org/mailman/listinfo/internetworkers>,	<mailto:internetworkers-request@lists.ibiblio.org?subject=unsubscribe>
List-Archive: <http://lists.ibiblio.org/pipermail/internetworkers>
List-Post: <mailto:internetworkers@lists.ibiblio.org>
List-Help: <mailto:internetworkers-request@lists.ibiblio.org?subject=help>
List-Subscribe:
	<http://lists.ibiblio.org/mailman/listinfo/internetworkers>,	<mailto:internetworkers-request@lists.ibiblio.org?subject=subscribe>
Sender: internetworkers-bounces@lists.ibiblio.org
Errors-To: internetworkers-bounces@lists.ibiblio.org


------=_Part_29756_30378337.1170458704014
Content-Type: multipart/alternative;  boundary="----=_Part_29757_4485752.1170458704014"


------=_Part_29757_4485752.1170458704014
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Disposition: inline
Content-Transfer-Encoding: 8bit

Cross-posting this because the topic should be of general interest.
Please accept my apologies if you received this multiple times. The
following press release was sent to local papers several weeks ago. In
case you missed it on their calendars, here goes:

Executive Summary
------------------------------
WHO: Greg Dekoenigsberg (Community Development Manager for Red Hat)
WHAT: One Laptop Per Child ( http://www.laptop.org/ )
HOW: Live presentation at the TriLUG meeting (http://www.trilug.org)
WHEN: Feb 8, 2007 at 7pm.
WHERE: Red Hat HQ (http://www.redhat.com/about/contact/ww/americas/raleigh.html)
ETC: This meeting (including the pizza) sponsored by InCentric
Solutions. http://www.incentric.com. Open to the public.

For Immediate Release
---------------------------------
At the February meeting of the Triangle Linux Users Group (TriLUG,
http://www.trilug.org/), Greg Dekoenigsberg, Red Hat's Community
Development Manager, will be giving a presentation on One Laptop Per
Child (OLPC), a project started at the MIT Media Lab that will develop
and market a $100 laptop to developing countries for use by children
in educational settings. These laptops incorporate various innovations
both to reduce cost and to make them appropriate for children in
remote environments, including dual-mode screens that are readable in
bright daylight, power via a hand crank, and ad-hoc wireless mesh
networking. The laptops will run a Linux-based Operating System
developed by Red Hat.

The meeting is open to the public. Free pizza and drinks will be
sponsored by InCentric Solutions, http://www.incentric.com

-- 
Cristóbal M. Palmer
TriLUG Vice Chair
"There are many roads to enlightenment, and thus many roads back to
the One True Debian" --crimsun

------=_Part_29757_4485752.1170458704014
Content-Type: text/calendar; method=REQUEST; name=invite.ics; charset=UTF-8
Content-Disposition: inline
Content-Transfer-Encoding: 8bit

BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTART:20070203T000000Z
DTEND:20070209T020000Z
DTSTAMP:20070202T232503Z
ORGANIZER;CN=Cristobal Palmer:MAILTO:cristobalpalmer@gmail.com
UID:cra6vugnvdtrsdjtuo17jsc2g4@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=trilug@trilug.org;X-NUM-GUESTS=0:MAILTO:trilug@trilug.org
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=trilug-announce@trilug.org;X-NUM-GUESTS=0:MAILTO:trilug-announce@tr
 ilug.org
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=internetworkers@lists.ibiblio.org;X-NUM-GUESTS=0:MAILTO:internetwor
 kers@lists.ibiblio.org
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=tribug-members@tribug.org;X-NUM-GUESTS=0:MAILTO:tribug-members@trib
 ug.org
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=labratz@metalab.unc.edu;X-NUM-GUESTS=0:MAILTO:labratz@metalab.unc.e
 du
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE
 ;CN=Cristobal Palmer;X-NUM-GUESTS=0:MAILTO:cristobalpalmer@gmail.com
CLASS:PRIVATE
CREATED:20070202T232454Z
DESCRIPTION:Cross-posting this because the topic should be of general inter
 est. Please accept my apologies if you received this multiple times. The fo
 llowing press release was sent to local papers several weeks ago. In case y
 ou missed it on their calendars\, here goes:\n\nExecutive Summary\n--------
 ----------------------\nWHO: Greg Dekoenigsberg (Community Development Mana
 ger for Red Hat)\nWHAT: One Laptop Per Child ( http://www.laptop.org/ )\nHO
 W: Live presentation at the TriLUG meeting (http://www.trilug.org)\nWHEN: F
 eb 8\, 2007 at 7pm.\nWHERE: Red Hat HQ (http://www.redhat.com/about/contact
 /ww/americas/raleigh.html)\nETC: This meeting (including the pizza) sponsor
 ed by InCentric\nSolutions. http://www.incentric.com. Open to the public.\n
 \nFor Immediate Release\n---------------------------------\nAt the February
  meeting of the Triangle Linux Users Group (TriLUG\,\nhttp://www.trilug.org
 /)\, Greg Dekoenigsberg\, Red Hat's Community\nDevelopment Manager\, will b
 e giving a presentation on One Laptop Per\nChild (OLPC)\, a project started
  at the MIT Media Lab that will develop\nand market a $100 laptop to develo
 ping countries for use by children\nin educational settings. These laptops 
 incorporate various innovations\nboth to reduce cost and to make them appro
 priate for children in\nremote environments\, including dual-mode screens t
 hat are readable in\nbright daylight\, power via a hand crank\, and ad-hoc 
 wireless mesh\nnetworking. The laptops will run a Linux-based Operating Sys
 tem\ndeveloped by Red Hat.\n\nThe meeting is open to the public. Free pizza
  and drinks will be\nsponsored by InCentric Solutions\, http://www.incentri
 c.com\n\n-- \nCristóbal M. Palmer\nTriLUG Vice Chair\n"There are many roads
  to enlightenment\, and thus many roads back to the One True Debian" --crim
 sun\n\nView your event at http://www.google.com/calendar/event?action=VIEW&
 ueid=cra6vugnvdtrsdjtuo17jsc2g4.
LAST-MODIFIED:20070202T232454Z
LOCATION:Red Hat HQ http://www.redhat.com/about/contact/ww/americas/raleigh
 .html
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Greg Dekoenigsberg on One Laptop Per Child
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

------=_Part_29757_4485752.1170458704014--

------=_Part_29756_30378337.1170458704014
Content-Type: application/ics; name="invite20070202T190000.ics"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="invite20070202T190000.ics"

QkVHSU46VkNBTEVOREFSDQpQUk9ESUQ6LS8vR29vZ2xlIEluYy8vR29vZ2xlIENhbGVuZGFyIDcw
LjkwNTQvL0VODQpWRVJTSU9OOjIuMA0KQ0FMU0NBTEU6R1JFR09SSUFODQpNRVRIT0Q6UkVRVUVT
VA0KQkVHSU46VkVWRU5UDQpEVFNUQVJUOjIwMDcwMjAzVDAwMDAwMFoNCkRURU5EOjIwMDcwMjA5
VDAyMDAwMFoNCkRUU1RBTVA6MjAwNzAyMDJUMjMyNTAzWg0KT1JHQU5JWkVSO0NOPUNyaXN0b2Jh
bCBQYWxtZXI6TUFJTFRPOmNyaXN0b2JhbHBhbG1lckBnbWFpbC5jb20NClVJRDpjcmE2dnVnbnZk
dHJzZGp0dW8xN2pzYzJnNEBnb29nbGUuY29tDQpBVFRFTkRFRTtDVVRZUEU9SU5ESVZJRFVBTDtS
T0xFPVJFUS1QQVJUSUNJUEFOVDtQQVJUU1RBVD1ORUVEUy1BQ1RJT047UlNWUD0NCiBUUlVFO0NO
PXRyaWx1Z0B0cmlsdWcub3JnO1gtTlVNLUdVRVNUUz0wOk1BSUxUTzp0cmlsdWdAdHJpbHVnLm9y
Zw0KQVRURU5ERUU7Q1VUWVBFPUlORElWSURVQUw7Uk9MRT1SRVEtUEFSVElDSVBBTlQ7UEFSVFNU
QVQ9TkVFRFMtQUNUSU9OO1JTVlA9DQogVFJVRTtDTj10cmlsdWctYW5ub3VuY2VAdHJpbHVnLm9y
ZztYLU5VTS1HVUVTVFM9MDpNQUlMVE86dHJpbHVnLWFubm91bmNlQHRyDQogaWx1Zy5vcmcNCkFU
VEVOREVFO0NVVFlQRT1JTkRJVklEVUFMO1JPTEU9UkVRLVBBUlRJQ0lQQU5UO1BBUlRTVEFUPU5F
RURTLUFDVElPTjtSU1ZQPQ0KIFRSVUU7Q049aW50ZXJuZXR3b3JrZXJzQGxpc3RzLmliaWJsaW8u
b3JnO1gtTlVNLUdVRVNUUz0wOk1BSUxUTzppbnRlcm5ldHdvcg0KIGtlcnNAbGlzdHMuaWJpYmxp
by5vcmcNCkFUVEVOREVFO0NVVFlQRT1JTkRJVklEVUFMO1JPTEU9UkVRLVBBUlRJQ0lQQU5UO1BB
UlRTVEFUPU5FRURTLUFDVElPTjtSU1ZQPQ0KIFRSVUU7Q049dHJpYnVnLW1lbWJlcnNAdHJpYnVn
Lm9yZztYLU5VTS1HVUVTVFM9MDpNQUlMVE86dHJpYnVnLW1lbWJlcnNAdHJpYg0KIHVnLm9yZw0K
QVRURU5ERUU7Q1VUWVBFPUlORElWSURVQUw7Uk9MRT1SRVEtUEFSVElDSVBBTlQ7UEFSVFNUQVQ9
TkVFRFMtQUNUSU9OO1JTVlA9DQogVFJVRTtDTj1sYWJyYXR6QG1ldGFsYWIudW5jLmVkdTtYLU5V
TS1HVUVTVFM9MDpNQUlMVE86bGFicmF0ekBtZXRhbGFiLnVuYy5lDQogZHUNCkFUVEVOREVFO0NV
VFlQRT1JTkRJVklEVUFMO1JPTEU9UkVRLVBBUlRJQ0lQQU5UO1BBUlRTVEFUPUFDQ0VQVEVEO1JT
VlA9VFJVRQ0KIDtDTj1DcmlzdG9iYWwgUGFsbWVyO1gtTlVNLUdVRVNUUz0wOk1BSUxUTzpjcmlz
dG9iYWxwYWxtZXJAZ21haWwuY29tDQpDTEFTUzpQUklWQVRFDQpDUkVBVEVEOjIwMDcwMjAyVDIz
MjQ1NFoNCkRFU0NSSVBUSU9OOkNyb3NzLXBvc3RpbmcgdGhpcyBiZWNhdXNlIHRoZSB0b3BpYyBz
aG91bGQgYmUgb2YgZ2VuZXJhbCBpbnRlcg0KIGVzdC4gUGxlYXNlIGFjY2VwdCBteSBhcG9sb2dp
ZXMgaWYgeW91IHJlY2VpdmVkIHRoaXMgbXVsdGlwbGUgdGltZXMuIFRoZSBmbw0KIGxsb3dpbmcg
cHJlc3MgcmVsZWFzZSB3YXMgc2VudCB0byBsb2NhbCBwYXBlcnMgc2V2ZXJhbCB3ZWVrcyBhZ28u
IEluIGNhc2UgeQ0KIG91IG1pc3NlZCBpdCBvbiB0aGVpciBjYWxlbmRhcnNcLCBoZXJlIGdvZXM6
XG5cbkV4ZWN1dGl2ZSBTdW1tYXJ5XG4tLS0tLS0tLQ0KIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS1c
bldITzogR3JlZyBEZWtvZW5pZ3NiZXJnIChDb21tdW5pdHkgRGV2ZWxvcG1lbnQgTWFuYQ0KIGdl
ciBmb3IgUmVkIEhhdClcbldIQVQ6IE9uZSBMYXB0b3AgUGVyIENoaWxkICggaHR0cDovL3d3dy5s
YXB0b3Aub3JnLyApXG5ITw0KIFc6IExpdmUgcHJlc2VudGF0aW9uIGF0IHRoZSBUcmlMVUcgbWVl
dGluZyAoaHR0cDovL3d3dy50cmlsdWcub3JnKVxuV0hFTjogRg0KIGViIDhcLCAyMDA3IGF0IDdw
bS5cbldIRVJFOiBSZWQgSGF0IEhRICho


------=_Part_29756_30378337.1170458704014--

--------------010508010705020604050502--

