Subject: [Fwd: Test Image]
From: Michael Barker <mbarker@buni.org>
To: tom@localhost
Content-Type: multipart/mixed; boundary="=-2+DeabYuUOigcABipoEQ"
Date: Sun, 14 Jan 2007 13:13:12 +0000
Message-Id: <1168780392.4824.4.camel@corona>
Mime-Version: 1.0
X-Mailer: Evolution 2.8.1 
X-Evolution-Source: pop://mikeb01@pop.gmail.com/


--=-2+DeabYuUOigcABipoEQ
Content-Type: text/plain
Content-Transfer-Encoding: 8bit

Check out the image.
-------- Forwarded Message --------
> From: Michael Barker <mike@middlesoft.co.uk>
> To: mike@middlesoft.co.uk
> Subject: Test Image
> Date: Sun, 14 Jan 2007 13:09:00 +0000
> 
> Here is buni's image.
> 
> 

--=-2+DeabYuUOigcABipoEQ
Content-Disposition: attachment; filename=buni1small.png
Content-Type: image/png; name=buni1small.png
Content-Transfer-Encoding: base64

iVBORw0KGgoAAAANSUhEUgAAAG0AAAApCAMAAAAI71ceAAADAFBMVEV1AAN3AAPOsZ3Nrp2bTTqQ
NjTStJ2JHgJyCQJfBAJ1CAKAERJcAQJkBgKkYVOFGgLZwqydUkSzfm27i3trCgK+koFbAAJvDQKG
Hx9iBgJyAAN9EQJoCALStqOnbmB/ERKSJgPp4cyJKCdiAwJ5DQJ5CgK4gW2LLSuNMC5yDwJ6BAbI
oo+BFQLm3cd1EAKyeGRgAgKNIwJ4EgJlAwJ6Ix3ZxLGrbFaGICBlCAJ2EQJ4GA/Qs53dzbltAwLT
uqqrb2FsCgKYQyy8iXODGBjh0r5jBAKqWjp5AgWAGAJeAQJwDAJoBAJmAwJuBAJpAgJ6FALBmYhn
BgJyDAKGHALInohtDAKXQz9sBAJkBAJ+FgK0emR8FQKROjd6BQd0DQJqAwLUtp2oYUiue221gnOF
KR23fGRhAQJnBAJ0BgJyBAJqBAJwBQKLIQKkVjp2BgJqCAJ8FAJyBgJ9DxBoBgJsCAJwBgJrBgLL
qJVvCAJvCgJxDgK5f2SVRTrPtKOdTzqaS0avdGF1BAKMQTihVDp9CQttBgKSNh7HppaDGAKEHR1s
BQJ2DQKDGgKfUjp0DAJbAQJ6CArHmoHIo5R6EQJzFQ+EIRB9CgyCHhN/EwKEMyp2EgKDFxilXEiZ
RzmTPy2KLR7i1cF4DwKAEwLXwKx/Jx13CwKOMh6RLBBiAQJkCAKJNyqTPTmRQzjg0Lm2iXt7DwLA
lYHVuKODFgKUMRDn38t8DA69j4FkAQKcPx5vAwKHJCOnWDqONip6Cwx6DA53AwV+Gw+IGwKSRTiM
Jg91BQKnZlVnAQKAFhd+AAN5AAOAAAN4AANdAwJgBAJhBQJfAwJgBQJdAgJpCgKUPjphBAJfAgKV
Qj6VPzt/GAKXRECBGQKPJAJ4CAKLHwJxAwJ9EhPj1L6cXlN1BQfYw7GVUEV0AwK6h3y1f3SwZ0mW
Qzh/Fw+jTSyFGgqQOCrcybTJnYGraFWYSDmzfGSKNSyweGSZQjKJJBKKKBB8AAN6AAN/AAN9AAN7
AAPt69Xx79laAAJ2V1x0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1wEBABsLeNfa8AAA
BcRJREFUWMPtlH1MU1cUwK8uRcWPEsDpwBgpuIFDEMFMNCzEqjAfoMJGFVYhBia2OL6ZZYnZYokI
8rGpHa7ZElAyZ9xYWAxxjEwTdNlgdizSqQXJliXbX9tM9r2dunPuvY+2UD/+WPrXfr3vvnPPO+/8
3rttyu4GEva/7b+ytbffbZ/GKDHizbwHMSImr1tGR9pHqZdX37vtbMF0yORj82n7JR/z1NlzllZv
3yj18unNHvUxLeAV9zHNgFI+unkeG8l8dMzHtWBqEx0Oxxc4BNdwEI/5co2GyNOMNbIe73Q4uG/E
9+3YMypjOMYcOCTXJdhn4UPBH+iauEn2GKMPdZZ4bCRz+2Gm612f0wzjdW/hGIKNp9vWEP5s2GP9
Q7FwPRdu8RDtiCbjmjXYXdheEHBZtF+bbLbs/qhKibBtieZga2FRbSLtz+Zp+BUSLg9BOIV0Yapm
JyGEu5BoD9x2llAz/m287YOZ7ty5i5OcnDxlJFs/kszxZ6vARunEc/ckXRAeXoEsq0Bdzc4a1O0j
RGdynO1nKOKqLAKbpyiKUnNih8fmZVlyL1QresPTKzg1iKJw376sZKlkWf39WRJFcR9RlG++S6lP
WX5ib0Vt+nKybSN4z4YlDQ0NcTTi4ijiM4FXEKoT71lbW4u+eu4TSAO7iggV4nYf2Xzk/fq99Vif
brFY1pFNtsTmcQl0cPgigQ+BKEIh3iaE9YgJ8fiusqs5OYpShB9FMZnE3qWcilp3ZoPFgreec7tz
c1VFquTN1KlIhAmp8gFyc3O3CaHl4MFaYWwmYRGiKDksJyeHwiKTydDcLL+qM6cWuS1nzuVuoK9P
9ay9L6lcmLAHISPXIY2NjfXNzQaDycQlrEjIDAaUNUrbus3n3TvORYlFQuqV2ZwPTm5HCgsLt/sw
ezZOXkbuQ+bOVX2kM0gbkmYwZGdnY179HZ4P3RFWsucSj9eu/QUkhYW7VTwhpeUTcGVXVwsK20gn
fHWN2NxgSEMYTbjKNpvr6qqmfvYtl8JKXgoLpderrEyERGp7Gg5lIrdu4ZEpInHOvHHjBhVUIseJ
rhakra1tLqeqqqrOjIa07DR28SJXmc2Y9LJ1LZIb6e7cnQgF1Bvg92MAx5AgaG2FEP66x3iKtKv5
+jQ+25MUXGq5QifMko4EaESb2bx/P8nKgoOpe9SinpiYmN7e3sjIyldwHR9fIDcyJC8PIA8JgsOH
AQ7n5a2GTZjSEpsgJDPzN4CTiXgcXwyrYwDu9PQsBggOLisrqyLJRXb79n4CE2Tb/DGpSt4KDX38
zp3Ozvj4n91NTaVQSo5SCJkDMAcJggMHIAgDmjElnqBVq23aCIdw3zsjIyN7ewFiYnp6yMZ9ZGG3
pQtT4+M9JWG+f5LPNmm1qCnFzhPlADg+TEpKAm4rL08awBmz5RP0BPiu2o3QWgAF3Z3kA3gDARiX
OhSyV5EXifGVK1f6+VOOujynVP1NvuYqBijGAwYGoNjlcm3FGcA1gMYDAEFB+F1qS6Ggry++u7ub
9p6+XOw7Po6CoaEhtA0NoQrxb3NPTLwsZZtWrFjxE/Uohq3owRXNAHgCl+sHKnnvncu4E9q+vr7u
7l9/xMTb3IY67mMR3uTfzJcj/ybCg4iIpflO+jg/wgqd0+nUxDonJ/NjcTXpjI1w5uPJGRHxqRNr
nv8Wq5eKZo88jZmjAF79mQ+xmpkwplfDp5hOo9Hhoamu1uiwnmasqBaHTvcEBnqNXjR7XezI9+xe
6KrZoF7nhd6I2UndpLiqw/EJDwYHdUcxoFmn4xeP6gbFrFbjha8ReVkyyxu7Xm/v8MlY7bNm2ewX
KLTZ52MBRfP1RqN+PgbGqRTlaLYbL9htajOa9XavbmzYG5uV07FKLFdZrTYrP1kp6hgettoo32HL
yLBZM3BpNQ7beGrYaLXyBsOr6BZa8QqjuEPCPgsk7M9Awv4JJOyPQML+DiTsr0DCPg8k/wIpVenV
HldpqQAAAABJRU5ErkJggg==


--=-2+DeabYuUOigcABipoEQ--

