Subject: [Fwd: Test Image]
From: Michael Barker <mbarker@buni.org>
To: tom@localhost
Content-Type: multipart/mixed; boundary="=-aqUdPSSJmLNPlfkFjcKR"
Date: Sun, 14 Jan 2007 13:13:12 +0000
Message-Id: <1168780392.4824.4.camel@corona>
Mime-Version: 1.0
X-Mailer: Evolution 2.8.1 
X-Evolution-Source: pop://mikeb01@pop.gmail.com/


--=-aqUdPSSJmLNPlfkFjcKR
Content-Type: text/plain
Content-Transfer-Encoding: 8bit

Check out the image.

--=-aqUdPSSJmLNPlfkFjcKR
Content-Disposition: inline
Content-Description: Forwarded message - Test Image
Content-Type: message/rfc822

From: <tom>
To: <tom@localhost>
Cc:
Bcc:
Subject: test
Date: Fri, 1 Dec 2006 16:07:58 +0000 (GMT)

test

--=-aqUdPSSJmLNPlfkFjcKR--

