expect "^220 .*$"
send   "HELO localhost"
expect "^250 .*$"
send   "MAIL FROM:<tom@localhost>"
expect "^250 .*$"
send   "RCPT TO:<tom@localhost>"
expect "^250 .*$"
send   "DATA"
expect "^354 .*$"
sendFile "mail/mailtest/etc/layout/test5.msg"
send   "."
expect "^250 .*$"
send   "QUIT"
expect "^221 .*$"
